# Generated by Django 4.0.5 on 2022-06-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='code',
            new_name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('AB', 'AB'), ('CO', 'CO'), ('GE', 'GE')], default=' ', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default=' ', max_length=40),
        ),
    ]
