# Generated by Django 4.0.5 on 2022-06-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_date_start_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='when',
            field=models.CharField(default='', max_length=40, verbose_name='Cuándo?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.CharField(default='', max_length=40, verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(verbose_name='Aporte económico'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(default='', max_length=40, verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('AB', 'AB'), ('CO', 'CO'), ('GE', 'GE')], default='', max_length=2, verbose_name='Tipo'),
        ),
    ]
