# Generated by Django 4.0.5 on 2022-06-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_when_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descripción'),
        ),
    ]
