# Generated by Django 4.0.5 on 2022-06-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='when',
            field=models.CharField(default='', max_length=100, verbose_name='Cuándo se dicta?'),
        ),
    ]
