# Generated by Django 4.0.5 on 2022-06-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_start',
            new_name='date_star',
        ),
    ]
