# Generated by Django 4.0.5 on 2022-06-20 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_date_start_student_date_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_star',
            new_name='date_start',
        ),
    ]
